// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEbXGrdSdrIjAX-HiixlvIrUaKFumMQ7I',
    appId: '1:276591760693:web:47a4b695990ea6e86ae87c',
    messagingSenderId: '276591760693',
    projectId: 'latihanfirebase-10990',
    authDomain: 'latihanfirebase-10990.firebaseapp.com',
    storageBucket: 'latihanfirebase-10990.firebasestorage.app',
    measurementId: 'G-9XPHZCLYGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP1NvzcdCLSgrc_Cgrlxr9b_zipVUkPKM',
    appId: '1:276591760693:android:6f1ebba921000e856ae87c',
    messagingSenderId: '276591760693',
    projectId: 'latihanfirebase-10990',
    storageBucket: 'latihanfirebase-10990.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL77tV2EHOt809PBJo11XgmZRZiWeiCJ0',
    appId: '1:276591760693:ios:645a2327092690df6ae87c',
    messagingSenderId: '276591760693',
    projectId: 'latihanfirebase-10990',
    storageBucket: 'latihanfirebase-10990.firebasestorage.app',
    iosClientId: '276591760693-a9vil7rnj0cfnlf5pmnnj21lka3qokm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.appsmarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL77tV2EHOt809PBJo11XgmZRZiWeiCJ0',
    appId: '1:276591760693:ios:645a2327092690df6ae87c',
    messagingSenderId: '276591760693',
    projectId: 'latihanfirebase-10990',
    storageBucket: 'latihanfirebase-10990.firebasestorage.app',
    iosClientId: '276591760693-a9vil7rnj0cfnlf5pmnnj21lka3qokm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.appsmarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEbXGrdSdrIjAX-HiixlvIrUaKFumMQ7I',
    appId: '1:276591760693:web:45e0143e3152c9916ae87c',
    messagingSenderId: '276591760693',
    projectId: 'latihanfirebase-10990',
    authDomain: 'latihanfirebase-10990.firebaseapp.com',
    storageBucket: 'latihanfirebase-10990.firebasestorage.app',
    measurementId: 'G-WE9YC81HM7',
  );
}
